# Generated by Django 4.2.4 on 2023-09-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumCover', models.TextField()),
                ('audio', models.TextField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Album', models.ManyToManyField(related_name='authors', to='app.album')),
                ('Single', models.ManyToManyField(related_name='authors', to='app.music')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='music_ids',
            field=models.ManyToManyField(related_name='albums', to='app.music'),
        ),
    ]
