# Generated by Django 4.2.4 on 2023-09-20 13:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='AlbumCover',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='Album',
        ),
        migrations.RemoveField(
            model_name='author',
            name='Single',
        ),
        migrations.RemoveField(
            model_name='album',
            name='music_ids',
        ),
        migrations.AddField(
            model_name='author',
            name='album',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='author',
            name='single',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='album',
            name='music_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
