# Generated by Django 4.2.4 on 2023-09-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_album_author_albums_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='music_ids',
            new_name='music',
        ),
    ]
