# Generated by Django 4.2.4 on 2023-09-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_music_ids_album_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
