# Generated by Django 4.2.4 on 2023-09-27 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_album_image_alter_author_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='audio',
        ),
        migrations.AddField(
            model_name='music',
            name='audioTrack',
            field=models.FileField(blank=True, upload_to='AudioTracks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])]),
        ),
    ]
