# Generated by Django 5.0.6 on 2024-07-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_author_options_alter_author_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
