# Generated by Django 5.0.6 on 2024-07-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='audioTrack',
            new_name='audiotrack',
        ),
    ]
